import { Employee } from './employees.interface';

export const EMPLOYEES: Employee[] = [
  {
    firstname: 'Vasya',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 1,
  },
  {
    firstname: 'Vasya',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 2,
  },
  {
    firstname: 'Vasya',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 3,
  },
  {
    firstname: 'Vasya',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 4,
  },
  {
    firstname: 'Vasya',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 5,
  },
  {
    firstname: 'Vasya',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 6,
  },
  {
    firstname: 'Vasya',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 7,
  },
  {
    firstname: '212',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 8,
  },
  {
    firstname: 'Vasya',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 9,
  },
  {
    firstname: 'Vasya',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 10,
  },
  {
    firstname: '212121',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 11,
  },
  {
    firstname: 'Vasya',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 12,
  },
  {
    firstname: '121',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 13,
  },
  {
    firstname: 'Vasya',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 14,
  },
  {
    firstname: 'Vasy2121a',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 15,
  },
  {
    firstname: 'Vasya',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 16,
  },
  {
    firstname: 'Vasya',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 17,
  },
  {
    firstname: 'Vasya',
    lastname: 'Pupkin',
    email: 'v.pupkin@gmail.com',
    department: 'Javascript',
    specialization: 'Angular',
    id: 18,
  },
];
